services:
  product-service:
    build:
      context: ./product_service
      dockerfile: Dockerfile
    env_file:
      - ./keys/awsKeys
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product_service_db:5432/db
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    container_name: product_service
    ports:
      - "8001:8000"
    networks:
      - internal
    depends_on:
      - product_service_db
      - kafka

  product_service_db:
    image: postgres
    container_name: product_service_db
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5001:5432"
    networks:
      - internal

  inventory_service:
    build:
      dockerfile: Dockerfile
      context: inventory_service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://inventory_service_db:5432/db
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    container_name: inventory_service
    ports:
      - "8002:8000"
    networks:
      - internal
    depends_on:
      - kafka
      - inventory_service_db

  inventory_service_db:
    image: postgres
    container_name: inventory_service_db
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5002:5432"
    networks:
      - internal

  account_service:
    build:
      dockerfile: Dockerfile
      context: account_service
    env_file:
      - ./keys/jwtKey
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://account_service_db:5432/db
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - AUTH_SERVICE_URL=http://auth-service:8000
    container_name: account_service
    ports:
      - "8003:8000"
    networks:
      - internal
    depends_on:
      - kafka
      - account_service_db

  account_service_db:
    image: postgres
    container_name: account_service_db
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5003:5432"
    networks:
      - internal

  auth-service:
    build:
      dockerfile: Dockerfile
      context: auth_service
    container_name: auth_service
    env_file:
      - ./keys/keycloakKeys
    depends_on:
      - keycloak
    ports:
      - "8004:8000"
    networks:
      - internal

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
      - "start-dev"
      - "--import-realm"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - internal

  api_gateway:
    build:
      dockerfile: Dockerfile
      context: ./api_gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
    networks:
      - internal

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
    networks:
      - internal

networks:
  internal:
    driver: bridge
